steps:
  # Create environment variables file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cat > env.yaml << EOF
        NODE_ENV: "production"
        JWT_EXPIRE: "30d"
        CORS_ORIGINS: "http://localhost:3000,https://prepalgo.web.app,https://www.prepalgo.com,https://prepalgo.com"
        EOF

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/prep-algo-backend', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/prep-algo-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'prep-algo-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/prep-algo-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--env-vars-file'
      - 'env.yaml'
      - '--set-secrets'
      - 'MONGO_URI=MONGO_URI:latest,JWT_SECRET=JWT_SECRET:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest'

images:
  - 'gcr.io/$PROJECT_ID/prep-algo-backend' 