// Dark Mode
export const GET_THEME = 'GET_THEME';
export const UPDATE_THEME = 'UPDATE_THEME';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_LIGHT_MODE = 'SET_LIGHT_MODE';
export const INITIALIZE_THEME = 'INITIALIZE_THEME';
export const SET_SYSTEM_THEME = 'SET_SYSTEM_THEME';
export const SET_USER_THEME_PREFERENCE = 'SET_USER_THEME_PREFERENCE';

// Color Scheme
export const SET_COLOR_SCHEME = 'SET_COLOR_SCHEME';
export const INITIALIZE_COLOR_SCHEME = 'INITIALIZE_COLOR_SCHEME';

// Login user
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Google Login
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAILURE = 'GOOGLE_LOGIN_FAILURE';

// Signup user
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Reset Auth
export const RESET_AUTH = 'RESET_AUTH';
export const RESET_AUTH_SUCCESS = 'RESET_AUTH_SUCCESS';

// Session Management
export const UPDATE_LAST_ACTIVITY = 'UPDATE_LAST_ACTIVITY';

// Modal
export const TOGGLE_CODE_MODAL = 'TOGGLE_CODE_MODAL';
export const SHOW_CODE_MODAL = 'SHOW_CODE_MODAL';
export const GET_CODE = 'GET_CODE';
export const GET_CODE_SUCCESS = 'GET_CODE_SUCCESS';
export const FETCH_CODE = 'FETCH_CODE';
export const FETCH_CODE_SUCCESS = 'FETCH_CODE_SUCCESS';
export const FETCH_CODE_ERROR = 'FETCH_CODE_ERROR';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const CLOSE_CODE_MODAL = 'CLOSE_CODE_MODAL';
export const CLOSE_CODE_MODAL_SUCCESS = 'CLOSE_CODE_MODAL_SUCCESS';

// Others
export const SHOW_FETCH_LOADING = 'SHOW_FETCH_LOADING';
export const HIDE_FETCH_LOADING = 'HIDE_FETCH_LOADING';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_ALL_QUESTIONS_WITHOUT_HISTORY = 'GET_ALL_QUESTIONS_WITHOUT_HISTORY';
export const GET_ALL_QUESTIONS_WITHOUT_HISTORY_SUCCESS = 'GET_ALL_QUESTIONS_WITHOUT_HISTORY_SUCCESS';
export const GET_ALL_QUESTIONS_WITHOUT_HISTORY_FAILURE = 'GET_ALL_QUESTIONS_WITHOUT_HISTORY_FAILURE';
export const GET_TOP_QUESTIONS = 'GET_TOP_QUESTIONS';
export const GET_SOLVED_QUESTIONS = 'GET_SOLVED_QUESTIONS';
export const MARK_QUESTION_AS_DONE = 'MARK_QUESTION_AS_DONE';
export const SET_QUESTION = 'SET_QUESTION';
export const SET_QUESTION_SUCCESS = 'SET_QUESTION_SUCCESS';

// User Info
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';
